minimum_pre_commit_version: "3.2"
exclude: "^$"
ci:
  skip: []
  autoupdate_schedule: quarterly

repos:
  # Sync Python and pre-commit package versions
  # pyproject.toml -> uv.lock
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: <placeholder_until_update_deps>
    hooks:
      - id: uv-lock
  # uv.lock -> .pre-commit-config.yaml
  - repo: https://github.com/tsvikas/sync-with-uv
    rev: <placeholder_until_update_deps>
    hooks:
      - id: sync-with-uv
  # .pre-commit-config.yaml -> .pre-commit-config.yaml
  - repo: https://github.com/pre-commit/sync-pre-commit-deps
    rev: <placeholder_until_update_deps>
    hooks:
      - id: sync-pre-commit-deps

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: <placeholder_until_update_deps>
    hooks:
      # Filesystem
      - id: check-illegal-windows-names
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      # Git related
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: forbid-submodules  # use subtree
      # Security
      - id: detect-private-key
      # Text encoding/formatting
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
      # Python
      - id: check-ast
      - id: check-docstring-first
      - id: debug-statements
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: requirements-txt-fixer
      # Symlinks
      - id: check-symlinks
      - id: destroyed-symlinks
      # File validation
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      # File formatting
      - id: pretty-format-json
        exclude_types: [jupyter]
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: <placeholder_until_update_deps>
    hooks:
      # Python files
      - id: python-check-blanket-noqa
      - id: python-check-blanket-type-ignore
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations
      # reStructuredText files
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      # UTF-8 encoding
      - id: text-unicode-replacement-char

  # All files
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: <placeholder_until_update_deps>
    hooks:
      - id: editorconfig-checker
        exclude_types: [jupyter]

  # Spell checking
  - repo: https://github.com/adhtruong/mirrors-typos
    rev: <placeholder_until_update_deps>
    hooks:
      - id: typos

  # Markdown files
  - repo: https://github.com/hukkin/mdformat
    rev: <placeholder_until_update_deps>
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          - mdformat-frontmatter
          - mdformat-footnote
          - mdformat-gfm-alerts

  # reStructuredText files
  - repo: https://github.com/PyCQA/doc8
    rev: <placeholder_until_update_deps>
    hooks:
      - id: doc8

  # Python files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: <placeholder_until_update_deps>
    hooks:
      - id: ruff-check
        alias: ruff-isort
        name: ruff isort
        args: [--select, I001, --fix]
      - id: ruff-format
      - id: ruff-check

  # YAML files
  - repo: https://github.com/adrienverge/yamllint
    rev: <placeholder_until_update_deps>
    hooks:
      - id: yamllint
